version: '3.8'

services:
  mail-sender:
    build: .
    container_name: mail-sender
    restart: always
    env_file:
      - .env
    ports:
      - "1000:1000"
    networks:
      - app-network

networks:
  app-network: